# Generated by Django 5.1 on 2024-08-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('paid', 'Paid')], max_length=50),
        ),
    ]
